server:
  port: 9999

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: "ffamexyz@gmail.com"
    password: "jzbf clew btkv tktt"
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create

  application:
    name: spring security application
  datasource:
    url: jdbc:postgresql://localhost/security_test
    username: postgres
    password: psql
    driver-class-name: org.postgresql.Driver